spring:
  data:
    mongodb:
      host: mongodb://localhost
      port: 27017
      database: standard
      username: admin
      password: laila@3715
      
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect 
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource: 
    url: jdbc:mysql://localhost:3306/standard?useTimezone=true&serverTimezone=UTC 
    driver-class-name: com.mysql.cj.jdbc.Driver 
    username: root
    password: laila@3715
    
#  profiles: prod
#  datasource: 
#    url: jdbc:mysql://localhost:3306/geo?useTimezone=true&serverTimezone=UTC 
#    driver-class-name: com.mysql.cj.jdbc.Driver 
#    username: root
#    password: laila3715