server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DNA-Mobile/config-server
          search-paths: auto, commerce, core, delivery, enterprise, finance, geo, people, restaurant, standard, telecom
          username: diretoria@dnambille.com.br
          password: laila@3715