server:
  port: 8888

spring:
  application:
    name: config  

  cloud:
    config:
      server:
        git:
          uri: https://github.com/DNA-Mobile/config-server
          search-paths: account, auto, commerce, core, delivery, enterprise, finance, geo, iam, people, restaurant, standard, telecom
          username: diretoria@dnambille.com.br
          password: laila@3715
          
    loadbalancer:
      ribbon:
        enabled: false
ribbon:
  eureka:
    enabled: false   
    
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
