server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dnamobile/config-server
          search-paths: telecom, geo
          username: diretoria@dnambille.com.br
          password: laila@3715