ribbon:
  eureka:
    enabled: false
    
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka