spring:
  main:
    allow-bean-definition-overriding: true
     
  data:
    mongodb:
      host: mongodb://localhost
      port: 27017
      database: auth
      username: admin
      password: laila@3715
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect 
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  datasource: 
    url: jdbc:mysql://localhost:3306/auth?useTimezone=true&serverTimezone=UTC 
    driver-class-name: com.mysql.cj.jdbc.Driver 
    username: root
    password: laila@3715
    
#  profiles: prod
#  datasource: 
#    url: jdbc:mysql://localhost:3306/geo?useTimezone=true&serverTimezone=UTC 
#    driver-class-name: com.mysql.cj.jdbc.Driver 
#    username: root
#    password: laila3715

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  
  prefix: /api
  ignoredServices: '*'
  routes:

# standard
    app:
      serviceId: app
      path: /app/**
#      strip-prefix: false
      
    user:
      serviceId: user
      path: /user/**
#      strip-prefix: false

    state:
      serviceId: state
      path: /state/**
#      strip-prefix: false
      
    feedback:
      serviceId: feedback
      path: /feedback/**
#      strip-prefix: false
      
    message:
      serviceId: message
      path: /message/**
#      strip-prefix: false
      
    tag:
      serviceId: tag
      path: /tag/**
#      strip-prefix: false

# geo
    estado:
      serviceId: estado
      path: /estado/**
#      strip-prefix: false
  
    cidade:
      serviceId: cidade
      path: /cidade/**
#      strip-prefix: false

    bairro:
      serviceId: bairro
      path: /bairro/**
#      strip-prefix: false

    logradouro:
      serviceId: logradouro
      path: /logradouro/**
#      strip-prefix: false

    endereco:
      serviceId: endereco
      path: /endereco/**
#      strip-prefix: false

    rota:
      serviceId: rota
      path: /rota/**
#      strip-prefix: false

# people      
    pessoafisica:
      serviceId: pessoafisica
      path: /pessoafisica/**
#      strip-prefix: false
      
    pessoajuridica:
      serviceId: pessoajuridica
      path: /pessoajuridica/**
#      strip-prefix: false
      
    contato:
      serviceId: contato
      path: /contato/**
#      strip-prefix: false

# auto
    veiculo:
      serviceId: veiculo
      path: /veiculo/**
#      strip-prefix: false
    
    modeloveiculo:
      serviceId: modeloveiculo
      path: /modeloveiculo/**
#      strip-prefix: false
      
    fabricanteveiculo:
      serviceId: fabricanteveiculo
      path: /fabricanteveiculo/**
#      strip-prefix: false
    
    motorista:
      serviceId: motorista
      path: /motorista/**
#      strip-prefix: false

# enterprise   
    cliente:
      serviceId: cliente
      path: /cliente/**
#      strip-prefix: false
    
    empresa:
      serviceId: empresa
      path: /empresa/**
#      strip-prefix: false
    
    catalogo:
      serviceId: catalogo
      path: /catalogo/**
#      strip-prefix: false
      
    atendimento:
      serviceId: atendimento
      path: /atendimento/**
#      strip-prefix: false
      
# commerce    
    estabelecimento:
      serviceId: estabelecimento
      path: /estabelecimento/**
#      strip-prefix: false
      
    pedido:
      serviceId: pedido
      path: /pedido/**
#      strip-prefix: false

    marca:
#      url: http://localhost:8002
      serviceId: marca
      path: /marca/**
#      strip-prefix: false
      
    produto:
      serviceId: produto
      path: /produto/**
#      strip-prefix: false

    service:
      serviceId: servico
      path: /servico/**
#      strip-prefix: false

# delivery
    configdelivery:
      serviceId: configdelivery
      path: /configdelivery/**
#      strip-prefix: false

    corrida:
      serviceId: corrida
      path: /corrida/**
#      strip-prefix: false

# restaurant
    restaurante:
      serviceId: restaurante
      path: /restaurante/**
#      strip-prefix: false

    prato:
      serviceId: prato
      path: /prato/**
#      strip-prefix: false

    comanda:
      serviceId: comanda
      path: /comanda/**
#      strip-prefix: false

# finance    
    gatewaypagamento:
      serviceId: gatewaypagamento
      path: /gatewaypagamento/**
#      strip-prefix: false

    banco:
      serviceId: banco
      path: /banco/**
#      strip-prefix: false
      
    contabancaria:
      serviceId: contabancaria
      path: /contabancaria/**
#      strip-prefix: false
      
    pagamento:
      serviceId: pagamento
      path: /pagamento/**
#      strip-prefix: false

marca:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: localhost:8002
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
    
fabricanteveiculo:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://fipeapi.appspot.com
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
    
modeloveiculo:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://fipeapi.appspot.com
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
