spring:
  main:
    allow-bean-definition-overriding: true
     
  data:
    mongodb:
      host: mongodb://localhost
      port: 27017
      database: restaurant
      username: admin
      password: laila@3715
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect 
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  datasource: 
    url: jdbc:mysql://localhost:3306/restaurant?useTimezone=true&serverTimezone=UTC 
    driver-class-name: com.mysql.cj.jdbc.Driver 
    username: root
    password: laila@3715
    
#  profiles: prod
#  datasource: 
#    url: jdbc:mysql://localhost:3306/geo?useTimezone=true&serverTimezone=UTC 
#    driver-class-name: com.mysql.cj.jdbc.Driver 
#    username: root
#    password: laila3715