spring:
  main:
    allow-bean-definition-overriding: true
  
  data:
    mongodb:
      host: mongodb://localhost
      port: 27017
      database: account
      username: admin
      password: laila@3715
      
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect 
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource: 
    url: jdbc:mysql://localhost:3306/account?useTimezone=true&serverTimezone=UTC 
    driver-class-name: com.mysql.jdbc.Driver 
    username: root
    password: laila@3715
    hikari:
      minIlde: 10
      idle-timeout: 10000
      maximumPoolSize: 30
    
#  profiles: prod
#  datasource: 
#    url: jdbc:mysql://localhost:3306/geo?useTimezone=true&serverTimezone=UTC 
#    driver-class-name: com.mysql.cj.jdbc.Driver 
#    username: root
#    password: laila3715