spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: diretoria@dnamobille.com.br
    password: laila@3715
    properties:
      mail: 
        smtp:
          auth: true
          starttls:
            enable: true